"""영어 문제은행 — capcha_service ms 브랜치 english 캡차 이식.

- playable(single): 09-grammar-choice(영문법 빈칸) 25 + 10-picture-sentence-match pick(그림→문장) 15
  = 40문항. 현재 게임 UI로 실플레이 + 서버 채점.
- playable=False(connect): picture-sentence-match 연결 유형 10 — 위젯 2차 통합 대상.
- 미이식(런타임 랜덤 생성기·오디오 — 정적 문제배열 없음): word-drag/sound-match/
  missing-letter/word-category-sort/word-puzzle/word-memory-match — 위젯 2차.
- 미이식(정적 배열은 있으나 조작형이라 선택지 문항으로 매핑 불가): alphabet-trace(따라쓰기)/
  sentence-order(어순 배열) — 위젯 2차.
- 원본 정답이 첫 보기에 몰려 있어(grammar options[0]) id 시드로 옵션 위치를 결정적 셔플했다.
- 정답(answer)은 이 서버 모듈에만 존재하며 문항 발급 응답에 포함하지 않는다.
"""

ENGLISH_FULL: list[dict] = [
    {'id': 'eng-grammar-g1-q1', 'topic': '영문법', 'stage': 1, 'type': 'single', 'prompt': '😊  Yesterday I ___ happy.', 'hint': '어제 있었던 일이에요 (과거).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'were'}, {'id': 'o2', 'emoji': '', 'text': 'was'}, {'id': 'o3', 'emoji': '', 'text': 'am'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'be동사 과거형'},
    {'id': 'eng-grammar-g1-q2', 'topic': '영문법', 'stage': 1, 'type': 'single', 'prompt': '🏫  They ___ at school yesterday.', 'hint': 'They(여럿) 다음엔?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'are'}, {'id': 'o2', 'emoji': '', 'text': 'was'}, {'id': 'o3', 'emoji': '', 'text': 'were'}], 'answer': 'o3', 'playable': 'o3', 'explain': 'be동사 과거형'},
    {'id': 'eng-grammar-g1-q3', 'topic': '영문법', 'stage': 1, 'type': 'single', 'prompt': '🤒  She ___ sick last night.', 'hint': '지난밤 = 과거!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'was'}, {'id': 'o2', 'emoji': '', 'text': 'is'}, {'id': 'o3', 'emoji': '', 'text': 'were'}], 'answer': 'o1', 'playable': 'o1', 'explain': 'be동사 과거형'},
    {'id': 'eng-grammar-g1-q4', 'topic': '영문법', 'stage': 1, 'type': 'single', 'prompt': '🏞️  We ___ in the park an hour ago.', 'hint': 'We 다음엔? (한 시간 전 = 과거)', 'options': [{'id': 'o1', 'emoji': '', 'text': 'was'}, {'id': 'o2', 'emoji': '', 'text': 'were'}, {'id': 'o3', 'emoji': '', 'text': 'are'}], 'answer': 'o2', 'playable': 'o2', 'explain': 'be동사 과거형'},
    {'id': 'eng-grammar-g1-q5', 'topic': '영문법', 'stage': 1, 'type': 'single', 'prompt': '🎬  The movie ___ fun yesterday.', 'hint': '하나(영화) + 과거!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'were'}, {'id': 'o2', 'emoji': '', 'text': 'is'}, {'id': 'o3', 'emoji': '', 'text': 'was'}], 'answer': 'o3', 'playable': 'o3', 'explain': 'be동사 과거형'},
    {'id': 'eng-grammar-g2-q1', 'topic': '영문법', 'stage': 2, 'type': 'single', 'prompt': '⚽  I ___ soccer yesterday.', 'hint': '어제 한 일 (과거형 -ed).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'play'}, {'id': 'o2', 'emoji': '', 'text': 'played'}, {'id': 'o3', 'emoji': '', 'text': 'plays'}], 'answer': 'o2', 'playable': 'o2', 'explain': '동사 과거형'},
    {'id': 'eng-grammar-g2-q2', 'topic': '영문법', 'stage': 2, 'type': 'single', 'prompt': '🚌  She ___ to school yesterday.', 'hint': 'go의 과거형은?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'go'}, {'id': 'o2', 'emoji': '', 'text': 'went'}, {'id': 'o3', 'emoji': '', 'text': 'goes'}], 'answer': 'o2', 'playable': 'o2', 'explain': '동사 과거형'},
    {'id': 'eng-grammar-g2-q3', 'topic': '영문법', 'stage': 2, 'type': 'single', 'prompt': '🍕  We ___ pizza last night.', 'hint': 'eat의 과거형은?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'eat'}, {'id': 'o2', 'emoji': '', 'text': 'ate'}, {'id': 'o3', 'emoji': '', 'text': 'eats'}], 'answer': 'o2', 'playable': 'o2', 'explain': '동사 과거형'},
    {'id': 'eng-grammar-g2-q4', 'topic': '영문법', 'stage': 2, 'type': 'single', 'prompt': '✉️  He ___ a letter yesterday.', 'hint': 'write의 과거형은?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'write'}, {'id': 'o2', 'emoji': '', 'text': 'wrote'}, {'id': 'o3', 'emoji': '', 'text': 'writes'}], 'answer': 'o2', 'playable': 'o2', 'explain': '동사 과거형'},
    {'id': 'eng-grammar-g2-q5', 'topic': '영문법', 'stage': 2, 'type': 'single', 'prompt': '📺  They ___ TV last night.', 'hint': '규칙 과거형 -ed!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'watches'}, {'id': 'o2', 'emoji': '', 'text': 'watch'}, {'id': 'o3', 'emoji': '', 'text': 'watched'}], 'answer': 'o3', 'playable': 'o3', 'explain': '동사 과거형'},
    {'id': 'eng-grammar-g3-q1', 'topic': '영문법', 'stage': 3, 'type': 'single', 'prompt': '👶  Look! The baby ___ crying.', 'hint': '지금 하고 있어요. (하나)', 'options': [{'id': 'o1', 'emoji': '', 'text': 'am'}, {'id': 'o2', 'emoji': '', 'text': 'is'}, {'id': 'o3', 'emoji': '', 'text': 'are'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-grammar-g3-q2', 'topic': '영문법', 'stage': 3, 'type': 'single', 'prompt': '🧒  The children ___ playing outside.', 'hint': 'children은 여럿!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'are'}, {'id': 'o2', 'emoji': '', 'text': 'am'}, {'id': 'o3', 'emoji': '', 'text': 'is'}], 'answer': 'o1', 'playable': 'o1', 'explain': '현재진행형'},
    {'id': 'eng-grammar-g3-q3', 'topic': '영문법', 'stage': 3, 'type': 'single', 'prompt': '📖  I ___ reading a book now.', 'hint': 'I 다음엔?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'am'}, {'id': 'o2', 'emoji': '', 'text': 'are'}, {'id': 'o3', 'emoji': '', 'text': 'is'}], 'answer': 'o1', 'playable': 'o1', 'explain': '현재진행형'},
    {'id': 'eng-grammar-g3-q4', 'topic': '영문법', 'stage': 3, 'type': 'single', 'prompt': '🎤  She is ___ a song now.', 'hint': 'be동사 다음엔 ~ing!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'singing'}, {'id': 'o2', 'emoji': '', 'text': 'sang'}, {'id': 'o3', 'emoji': '', 'text': 'sing'}], 'answer': 'o1', 'playable': 'o1', 'explain': '현재진행형'},
    {'id': 'eng-grammar-g3-q5', 'topic': '영문법', 'stage': 3, 'type': 'single', 'prompt': '⚽  We are ___ soccer now.', 'hint': 'be동사 다음엔 ~ing!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'played'}, {'id': 'o2', 'emoji': '', 'text': 'playing'}, {'id': 'o3', 'emoji': '', 'text': 'play'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-grammar-g4-q1', 'topic': '영문법', 'stage': 4, 'type': 'single', 'prompt': '🐘  An elephant is ___ than a cat.', 'hint': '둘을 비교해요 (-er than).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'bigger'}, {'id': 'o2', 'emoji': '', 'text': 'big'}, {'id': 'o3', 'emoji': '', 'text': 'biggest'}], 'answer': 'o1', 'playable': 'o1', 'explain': '비교급'},
    {'id': 'eng-grammar-g4-q2', 'topic': '영문법', 'stage': 4, 'type': 'single', 'prompt': '🐆  A cheetah is ___ than a dog.', 'hint': '더 빠른! (-er than)', 'options': [{'id': 'o1', 'emoji': '', 'text': 'fastest'}, {'id': 'o2', 'emoji': '', 'text': 'fast'}, {'id': 'o3', 'emoji': '', 'text': 'faster'}], 'answer': 'o3', 'playable': 'o3', 'explain': '비교급'},
    {'id': 'eng-grammar-g4-q3', 'topic': '영문법', 'stage': 4, 'type': 'single', 'prompt': '📦  This box is ___ than that one.', 'hint': '무게를 비교해요 (-ier than).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'heaviest'}, {'id': 'o2', 'emoji': '', 'text': 'heavy'}, {'id': 'o3', 'emoji': '', 'text': 'heavier'}], 'answer': 'o3', 'playable': 'o3', 'explain': '비교급'},
    {'id': 'eng-grammar-g4-q4', 'topic': '영문법', 'stage': 4, 'type': 'single', 'prompt': '🐦  Birds ___ fly high.', 'hint': '~할 수 있다!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'can'}, {'id': 'o2', 'emoji': '', 'text': 'cans'}, {'id': 'o3', 'emoji': '', 'text': 'do'}], 'answer': 'o1', 'playable': 'o1', 'explain': '조동사'},
    {'id': 'eng-grammar-g4-q5', 'topic': '영문법', 'stage': 4, 'type': 'single', 'prompt': '📏  He is ___ than his brother.', 'hint': '키를 비교해요 (-er than).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'tall'}, {'id': 'o2', 'emoji': '', 'text': 'taller'}, {'id': 'o3', 'emoji': '', 'text': 'tallest'}], 'answer': 'o2', 'playable': 'o2', 'explain': '비교급'},
    {'id': 'eng-grammar-g5-q1', 'topic': '영문법', 'stage': 5, 'type': 'single', 'prompt': '🐱  The cat is ___ the box.', 'hint': '고양이가 상자 위에 있어요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'under'}, {'id': 'o2', 'emoji': '', 'text': 'on'}, {'id': 'o3', 'emoji': '', 'text': 'in'}], 'answer': 'o2', 'playable': 'o2', 'explain': '전치사'},
    {'id': 'eng-grammar-g5-q2', 'topic': '영문법', 'stage': 5, 'type': 'single', 'prompt': '🎂  ___ is your birthday?', 'hint': '"언제"인지 물어봐요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'When'}, {'id': 'o2', 'emoji': '', 'text': 'What'}, {'id': 'o3', 'emoji': '', 'text': 'Who'}], 'answer': 'o1', 'playable': 'o1', 'explain': '의문사'},
    {'id': 'eng-grammar-g5-q3', 'topic': '영문법', 'stage': 5, 'type': 'single', 'prompt': '🚶  ___ are you going?', 'hint': '"어디로" 가는지 물어봐요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'What'}, {'id': 'o2', 'emoji': '', 'text': 'When'}, {'id': 'o3', 'emoji': '', 'text': 'Where'}], 'answer': 'o3', 'playable': 'o3', 'explain': '의문사'},
    {'id': 'eng-grammar-g5-q4', 'topic': '영문법', 'stage': 5, 'type': 'single', 'prompt': '⚽  The ball is ___ the table.', 'hint': '공이 탁자 아래에 있어요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'on'}, {'id': 'o2', 'emoji': '', 'text': 'next'}, {'id': 'o3', 'emoji': '', 'text': 'under'}], 'answer': 'o3', 'playable': 'o3', 'explain': '전치사'},
    {'id': 'eng-grammar-g5-q5', 'topic': '영문법', 'stage': 5, 'type': 'single', 'prompt': '👧  ___ is that girl?', 'hint': '"누구"인지 물어봐요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'Who'}, {'id': 'o2', 'emoji': '', 'text': 'What'}, {'id': 'o3', 'emoji': '', 'text': 'Where'}], 'answer': 'o1', 'playable': 'o1', 'explain': '의문사'},
    {'id': 'eng-picture-v1-q1', 'topic': '그림·문장', 'stage': 1, 'type': 'single', 'prompt': '😴🐱  그림에 맞는 문장을 골라보세요.', 'hint': '고양이가 지금 무엇을 하고 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The cat is running in the park.'}, {'id': 'o2', 'emoji': '', 'text': 'The cat is sleeping on the sofa.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-picture-v1-q2', 'topic': '그림·문장', 'stage': 1, 'type': 'single', 'prompt': '🏃🐶  그림에 맞는 문장을 골라보세요.', 'hint': '강아지가 무엇을 하고 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The dog is eating dinner.'}, {'id': 'o2', 'emoji': '', 'text': 'The dog is running fast.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-picture-v1-q3', 'topic': '그림·문장', 'stage': 1, 'type': 'single', 'prompt': '📖👧  그림에 맞는 문장을 골라보세요.', 'hint': '소녀가 무엇을 하고 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The girl is reading a book.'}, {'id': 'o2', 'emoji': '', 'text': 'The girl is drawing a picture.'}], 'answer': 'o1', 'playable': 'o1', 'explain': '현재진행형'},
    {'id': 'eng-picture-v1-q4', 'topic': '그림·문장', 'stage': 1, 'type': 'single', 'prompt': '🏊  그림에 맞는 문장을 골라보세요.', 'hint': '무엇을 하고 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The boy is swimming in the pool.'}, {'id': 'o2', 'emoji': '', 'text': 'The boy is flying a kite.'}], 'answer': 'o1', 'playable': 'o1', 'explain': '현재진행형'},
    {'id': 'eng-picture-v1-q5', 'topic': '그림·문장', 'stage': 1, 'type': 'single', 'prompt': '🎤  그림에 맞는 문장을 골라보세요.', 'hint': '무엇을 하고 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'She is washing the dishes.'}, {'id': 'o2', 'emoji': '', 'text': 'She is singing a song.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-picture-v2-q1', 'topic': '그림·문장', 'stage': 2, 'type': 'single', 'prompt': '🌧️☂️  그림에 맞는 문장을 골라보세요.', 'hint': '어제 있었던 일이에요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'It is sunny today.'}, {'id': 'o2', 'emoji': '', 'text': 'It will snow tomorrow.'}, {'id': 'o3', 'emoji': '', 'text': 'It rained yesterday.'}], 'answer': 'o3', 'playable': 'o3', 'explain': '과거형'},
    {'id': 'eng-picture-v2-q2', 'topic': '그림·문장', 'stage': 2, 'type': 'single', 'prompt': '📘🪑  그림에 맞는 문장을 골라보세요.', 'hint': '책이 어디에 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The book is under the chair.'}, {'id': 'o2', 'emoji': '', 'text': 'The book is in the bag.'}, {'id': 'o3', 'emoji': '', 'text': 'The book is on the desk.'}], 'answer': 'o3', 'playable': 'o3', 'explain': '전치사'},
    {'id': 'eng-picture-v2-q3', 'topic': '그림·문장', 'stage': 2, 'type': 'single', 'prompt': '🍽️🐶  그림에 맞는 문장을 골라보세요.', 'hint': '강아지가 한 일이에요.', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The dog slept all day.'}, {'id': 'o2', 'emoji': '', 'text': 'The dog ate all the food.'}, {'id': 'o3', 'emoji': '', 'text': 'The bird flew away.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '과거형'},
    {'id': 'eng-picture-v2-q4', 'topic': '그림·문장', 'stage': 2, 'type': 'single', 'prompt': '🐦🐦🐦  그림에 맞는 문장을 골라보세요.', 'hint': '새가 몇 마리인가요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'There are three birds in the tree.'}, {'id': 'o2', 'emoji': '', 'text': 'There is one bird in the tree.'}, {'id': 'o3', 'emoji': '', 'text': 'There are two cats on the roof.'}], 'answer': 'o1', 'playable': 'o1', 'explain': '복수'},
    {'id': 'eng-picture-v2-q5', 'topic': '그림·문장', 'stage': 2, 'type': 'single', 'prompt': '🦒  그림에 맞는 문장을 골라보세요.', 'hint': '기린은 어떤가요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The giraffe is smaller than a mouse.'}, {'id': 'o2', 'emoji': '', 'text': 'The giraffe is taller than the tree.'}, {'id': 'o3', 'emoji': '', 'text': 'The giraffe is shorter than the cat.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '비교급'},
    {'id': 'eng-picture-v3-q1', 'topic': '그림·문장', 'stage': 3, 'type': 'single', 'prompt': '😴🐱  비슷한 문장을 잘 읽고 골라보세요.', 'hint': '주어와 동작을 모두 확인!', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The cat is sitting on the bed.'}, {'id': 'o2', 'emoji': '', 'text': 'The cat is sleeping on the bed.'}, {'id': 'o3', 'emoji': '', 'text': 'The dog is sleeping on the bed.'}, {'id': 'o4', 'emoji': '', 'text': 'The cat is sleeping under the bed.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '현재진행형'},
    {'id': 'eng-picture-v3-q2', 'topic': '그림·문장', 'stage': 3, 'type': 'single', 'prompt': '🏫👦  비슷한 문장을 잘 읽고 골라보세요.', 'hint': '지금 하는 일이에요 (현재진행형).', 'options': [{'id': 'o1', 'emoji': '', 'text': 'He is going to school now.'}, {'id': 'o2', 'emoji': '', 'text': 'She is going to school now.'}, {'id': 'o3', 'emoji': '', 'text': 'He will go to school tomorrow.'}, {'id': 'o4', 'emoji': '', 'text': 'He went to school yesterday.'}], 'answer': 'o1', 'playable': 'o1', 'explain': '시제'},
    {'id': 'eng-picture-v3-q3', 'topic': '그림·문장', 'stage': 3, 'type': 'single', 'prompt': '⚽🪑  비슷한 문장을 잘 읽고 골라보세요.', 'hint': '공이 정확히 어디에 있나요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The ball is behind the chair.'}, {'id': 'o2', 'emoji': '', 'text': 'The ball is under the chair.'}, {'id': 'o3', 'emoji': '', 'text': 'The ball is next to the chair.'}, {'id': 'o4', 'emoji': '', 'text': 'The ball is on the chair.'}], 'answer': 'o2', 'playable': 'o2', 'explain': '전치사'},
    {'id': 'eng-picture-v3-q4', 'topic': '그림·문장', 'stage': 3, 'type': 'single', 'prompt': '🐘🐭  비슷한 문장을 잘 읽고 골라보세요.', 'hint': '누가 더 큰가요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'The elephant is bigger than the mouse.'}, {'id': 'o2', 'emoji': '', 'text': 'The mouse is taller than the elephant.'}, {'id': 'o3', 'emoji': '', 'text': 'The elephant is smaller than the mouse.'}, {'id': 'o4', 'emoji': '', 'text': 'The mouse is bigger than the elephant.'}], 'answer': 'o1', 'playable': 'o1', 'explain': '비교급'},
    {'id': 'eng-picture-v3-q5', 'topic': '그림·문장', 'stage': 3, 'type': 'single', 'prompt': '🐶🐶👧  비슷한 문장을 잘 읽고 골라보세요.', 'hint': '몇 마리이고 누구의 것인가요?', 'options': [{'id': 'o1', 'emoji': '', 'text': 'He has two dogs.'}, {'id': 'o2', 'emoji': '', 'text': 'She has two cats.'}, {'id': 'o3', 'emoji': '', 'text': 'She has two dogs.'}, {'id': 'o4', 'emoji': '', 'text': 'She has one dog.'}], 'answer': 'o3', 'playable': 'o3', 'explain': '소유·복수'},
    {'id': 'eng-picture-v4-q1', 'topic': '그림·문장', 'stage': 4, 'type': 'connect', 'prompt': '그림과 문장을 알맞게 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '현재진행형'},
    {'id': 'eng-picture-v4-q2', 'topic': '그림·문장', 'stage': 4, 'type': 'connect', 'prompt': '그림과 문장을 알맞게 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '비교급'},
    {'id': 'eng-picture-v4-q3', 'topic': '그림·문장', 'stage': 4, 'type': 'connect', 'prompt': '그림과 문장을 알맞게 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '과거형'},
    {'id': 'eng-picture-v4-q4', 'topic': '그림·문장', 'stage': 4, 'type': 'connect', 'prompt': '그림과 문장을 알맞게 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '전치사'},
    {'id': 'eng-picture-v4-q5', 'topic': '그림·문장', 'stage': 4, 'type': 'connect', 'prompt': '그림과 문장을 알맞게 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '현재진행형'},
    {'id': 'eng-picture-v5-q1', 'topic': '그림·문장', 'stage': 5, 'type': 'connect', 'prompt': '그림 3개와 문장 3개를 모두 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '현재진행형'},
    {'id': 'eng-picture-v5-q2', 'topic': '그림·문장', 'stage': 5, 'type': 'connect', 'prompt': '그림 3개와 문장 3개를 모두 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '과거형'},
    {'id': 'eng-picture-v5-q3', 'topic': '그림·문장', 'stage': 5, 'type': 'connect', 'prompt': '그림 3개와 문장 3개를 모두 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '전치사'},
    {'id': 'eng-picture-v5-q4', 'topic': '그림·문장', 'stage': 5, 'type': 'connect', 'prompt': '그림 3개와 문장 3개를 모두 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '비교급'},
    {'id': 'eng-picture-v5-q5', 'topic': '그림·문장', 'stage': 5, 'type': 'connect', 'prompt': '그림 3개와 문장 3개를 모두 연결해보세요.', 'hint': '', 'options': [], 'answer': None, 'playable': False, 'explain': '복합'},
]
