"""영어 듣기 문제은행 — capcha_service ms 02-sound-match 이식.

소리(단어 발음 .m4a)를 듣고 맞는 그림(이모지)을 고르는 듣기 캡차.
- 오디오는 불투명 이름(snd-NN.m4a)으로 백엔드가 서빙 — 파일명으로 정답(단어) 유출 방지.
- 보기는 이모지만(텍스트 없음), 위치는 id 시드 셔플 — 봇은 음성인식 없이 못 풀고 URL/보기로도 정답 불가.
- AUDIO_MAP: 단어→불투명 파일명 (서빙 화이트리스트). 정답(answer)·정답단어(explain)는 서버 전용.
"""

ENGLISH_LISTEN: list[dict] = [
    {'id': 'eng-listen-01', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍎', 'text': ''}, {'id': 'o2', 'emoji': '✏️', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-01.m4a', 'explain': 'apple'},
    {'id': 'eng-listen-02', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🎒', 'text': ''}, {'id': 'o2', 'emoji': '📘', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-02.m4a', 'explain': 'bag'},
    {'id': 'eng-listen-03', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '⚽', 'text': ''}, {'id': 'o2', 'emoji': '📘', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-03.m4a', 'explain': 'ball'},
    {'id': 'eng-listen-04', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍌', 'text': ''}, {'id': 'o2', 'emoji': '🔵', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-04.m4a', 'explain': 'banana'},
    {'id': 'eng-listen-05', 'topic': '영어 듣기', 'stage': 1, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐻', 'text': ''}, {'id': 'o2', 'emoji': '🍐', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-05.m4a', 'explain': 'bear'},
    {'id': 'eng-listen-06', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '⚽', 'text': ''}, {'id': 'o2', 'emoji': '📘', 'text': ''}, {'id': 'o3', 'emoji': '🐦', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'audio': 'snd-06.m4a', 'explain': 'bird'},
    {'id': 'eng-listen-07', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🔵', 'text': ''}, {'id': 'o2', 'emoji': '📘', 'text': ''}, {'id': 'o3', 'emoji': '🐻', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-07.m4a', 'explain': 'blue'},
    {'id': 'eng-listen-08', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐦', 'text': ''}, {'id': 'o2', 'emoji': '⚽', 'text': ''}, {'id': 'o3', 'emoji': '📘', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'audio': 'snd-08.m4a', 'explain': 'book'},
    {'id': 'eng-listen-09', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🚗', 'text': ''}, {'id': 'o2', 'emoji': '🧢', 'text': ''}, {'id': 'o3', 'emoji': '🐱', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-09.m4a', 'explain': 'cap'},
    {'id': 'eng-listen-10', 'topic': '영어 듣기', 'stage': 2, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🚗', 'text': ''}, {'id': 'o2', 'emoji': '🐱', 'text': ''}, {'id': 'o3', 'emoji': '🧢', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-10.m4a', 'explain': 'car'},
    {'id': 'eng-listen-11', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐱', 'text': ''}, {'id': 'o2', 'emoji': '🚗', 'text': ''}, {'id': 'o3', 'emoji': '🧢', 'text': ''}, {'id': 'o4', 'emoji': '🐮', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-11.m4a', 'explain': 'cat'},
    {'id': 'eng-listen-12', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🪑', 'text': ''}, {'id': 'o2', 'emoji': '🐻', 'text': ''}, {'id': 'o3', 'emoji': '🍎', 'text': ''}, {'id': 'o4', 'emoji': '✏️', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-12.m4a', 'explain': 'chair'},
    {'id': 'eng-listen-13', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐮', 'text': ''}, {'id': 'o2', 'emoji': '🚗', 'text': ''}, {'id': 'o3', 'emoji': '🧢', 'text': ''}, {'id': 'o4', 'emoji': '🐱', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-13.m4a', 'explain': 'cow'},
    {'id': 'eng-listen-14', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍇', 'text': ''}, {'id': 'o2', 'emoji': '🐶', 'text': ''}, {'id': 'o3', 'emoji': '🍊', 'text': ''}, {'id': 'o4', 'emoji': '🍐', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-14.m4a', 'explain': 'dog'},
    {'id': 'eng-listen-15', 'topic': '영어 듣기', 'stage': 3, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍎', 'text': ''}, {'id': 'o2', 'emoji': '🧢', 'text': ''}, {'id': 'o3', 'emoji': '🐟', 'text': ''}, {'id': 'o4', 'emoji': '🐦', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'audio': 'snd-15.m4a', 'explain': 'fish'},
    {'id': 'eng-listen-16', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍇', 'text': ''}, {'id': 'o2', 'emoji': '🐱', 'text': ''}, {'id': 'o3', 'emoji': '⚽', 'text': ''}, {'id': 'o4', 'emoji': '🍎', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-16.m4a', 'explain': 'grape'},
    {'id': 'eng-listen-17', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🟢', 'text': ''}, {'id': 'o2', 'emoji': '✏️', 'text': ''}, {'id': 'o3', 'emoji': '⚽', 'text': ''}, {'id': 'o4', 'emoji': '🐻', 'text': ''}], 'answer': 'o1', 'playable': 'o1', 'audio': 'snd-17.m4a', 'explain': 'green'},
    {'id': 'eng-listen-18', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '✏️', 'text': ''}, {'id': 'o2', 'emoji': '🍊', 'text': ''}, {'id': 'o3', 'emoji': '🟢', 'text': ''}, {'id': 'o4', 'emoji': '🍇', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-18.m4a', 'explain': 'orange'},
    {'id': 'eng-listen-19', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐻', 'text': ''}, {'id': 'o2', 'emoji': '🍐', 'text': ''}, {'id': 'o3', 'emoji': '🍑', 'text': ''}, {'id': 'o4', 'emoji': '🖊️', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'audio': 'snd-19.m4a', 'explain': 'peach'},
    {'id': 'eng-listen-20', 'topic': '영어 듣기', 'stage': 4, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍑', 'text': ''}, {'id': 'o2', 'emoji': '🍐', 'text': ''}, {'id': 'o3', 'emoji': '🖊️', 'text': ''}, {'id': 'o4', 'emoji': '🐻', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-20.m4a', 'explain': 'pear'},
    {'id': 'eng-listen-21', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍐', 'text': ''}, {'id': 'o2', 'emoji': '🖊️', 'text': ''}, {'id': 'o3', 'emoji': '🐻', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-21.m4a', 'explain': 'pen'},
    {'id': 'eng-listen-22', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🍐', 'text': ''}, {'id': 'o2', 'emoji': '✏️', 'text': ''}, {'id': 'o3', 'emoji': '🖊️', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-22.m4a', 'explain': 'pencil'},
    {'id': 'eng-listen-23', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🐶', 'text': ''}, {'id': 'o2', 'emoji': '🪑', 'text': ''}, {'id': 'o3', 'emoji': '🔴', 'text': ''}], 'answer': 'o3', 'playable': 'o3', 'audio': 'snd-23.m4a', 'explain': 'red'},
    {'id': 'eng-listen-24', 'topic': '영어 듣기', 'stage': 5, 'type': 'listen', 'prompt': '소리를 듣고 맞는 그림을 골라보세요.', 'hint': '🔊 버튼을 눌러 단어를 들어요.', 'options': [{'id': 'o1', 'emoji': '🟢', 'text': ''}, {'id': 'o2', 'emoji': '🟡', 'text': ''}, {'id': 'o3', 'emoji': '🖊️', 'text': ''}], 'answer': 'o2', 'playable': 'o2', 'audio': 'snd-24.m4a', 'explain': 'yellow'},
]

# 서빙 허용 오디오 파일 화이트리스트 (경로 조작 차단용)
AUDIO_FILES = frozenset(q['audio'] for q in ENGLISH_LISTEN)
