"""생활 과목 문제은행 — capcha_service(ms 브랜치) 생활안전 캡챠 스위트에서 이식.

출처: github.com/catchap-captcha/capcha_service (ms) — 팀원 작성 문항 그대로 사용.
single(하나 고르기) 유형만 1차 이식 (order/connect/드래그 조작형은 위젯 전용 — 2차).
정답(answer)은 이 모듈(서버)에만 존재하며 API 응답에 절대 포함하지 않는다.
"""

LIFE_QUESTIONS: list[dict] = [
    {"id": "life-01-traffic-safety-l1-q1", "topic": "교통안전", "prompt": "길을 건널 때 안전한 행동을 골라보세요.", "hint": "신호등을 잘 보고 골라요.", "options": [{"id": "o1", "emoji": "🟢", "text": "초록불에 건너기"}, {"id": "o2", "emoji": "🔴", "text": "빨간불에 뛰어가기"}, {"id": "o3", "emoji": "🚗", "text": "차도에서 장난치기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l1-q2", "topic": "교통안전", "prompt": "횡단보도를 건널 때 바른 행동은?", "hint": "차가 멈췄는지 확인해요.", "options": [{"id": "o1", "emoji": "👀", "text": "좌우를 살피고 건너기"}, {"id": "o2", "emoji": "📱", "text": "휴대폰을 보며 건너기"}, {"id": "o3", "emoji": "🏃", "text": "뒤돌아보며 뛰기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l1-q3", "topic": "교통안전", "prompt": "차에 탈 때 안전한 행동을 골라보세요.", "hint": "몸을 지켜주는 것을 떠올려요.", "options": [{"id": "o1", "emoji": "🔒", "text": "안전벨트 매기"}, {"id": "o2", "emoji": "🚪", "text": "달리는 차에서 문 열기"}, {"id": "o3", "emoji": "🪟", "text": "창밖으로 손 내밀기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l1-q4", "topic": "교통안전", "prompt": "걸을 때 안전한 곳은 어디일까요?", "hint": "사람이 다니는 길을 떠올려요.", "options": [{"id": "o1", "emoji": "🚶", "text": "인도(보도)로 걷기"}, {"id": "o2", "emoji": "🛣️", "text": "차도 한가운데로 걷기"}, {"id": "o3", "emoji": "🚧", "text": "공사장 안으로 걷기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l1-q5", "topic": "교통안전", "prompt": "자전거를 탈 때 안전한 행동은?", "hint": "머리를 지켜주는 것을 떠올려요.", "options": [{"id": "o1", "emoji": "⛑️", "text": "헬멧을 쓰고 타기"}, {"id": "o2", "emoji": "🙌", "text": "두 손 놓고 타기"}, {"id": "o3", "emoji": "🌙", "text": "불 없이 밤에 빠르게 타기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l2-q1", "topic": "교통안전", "prompt": "위험한 행동을 찾아보세요.", "hint": "신호를 어기면 위험해요.", "options": [{"id": "o1", "emoji": "🚸", "text": "횡단보도로 건너기"}, {"id": "o2", "emoji": "🟢", "text": "신호등을 보고 건너기"}, {"id": "o3", "emoji": "🔴", "text": "빨간불에 뛰어가기"}], "answer": "o3"},
    {"id": "life-01-traffic-safety-l2-q2", "topic": "교통안전", "prompt": "하면 안 되는 위험한 행동은?", "hint": "차 사이는 안 보여요.", "options": [{"id": "o1", "emoji": "🚗", "text": "주차된 차 사이로 갑자기 뛰어나가기"}, {"id": "o2", "emoji": "🚦", "text": "신호를 기다리기"}, {"id": "o3", "emoji": "🤚", "text": "손을 들고 건너기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l2-q3", "topic": "교통안전", "prompt": "위험한 행동을 골라보세요.", "hint": "공은 차도로 굴러가기 쉬워요.", "options": [{"id": "o1", "emoji": "🏞️", "text": "공원에서 공놀이하기"}, {"id": "o2", "emoji": "⚽", "text": "차도에서 공놀이하기"}, {"id": "o3", "emoji": "🛝", "text": "놀이터에서 놀기"}], "answer": "o2"},
    {"id": "life-01-traffic-safety-l2-q4", "topic": "교통안전", "prompt": "버스를 기다릴 때 위험한 행동은?", "hint": "차도 쪽은 위험해요.", "options": [{"id": "o1", "emoji": "🚏", "text": "정류장 안에서 기다리기"}, {"id": "o2", "emoji": "🛣️", "text": "차도로 내려가 기웃거리기"}, {"id": "o3", "emoji": "🧍", "text": "줄 서서 기다리기"}], "answer": "o2"},
    {"id": "life-01-traffic-safety-l2-q5", "topic": "교통안전", "prompt": "길에서 위험한 행동을 찾아보세요.", "hint": "앞을 못 보면 위험해요.", "options": [{"id": "o1", "emoji": "👀", "text": "앞을 보며 걷기"}, {"id": "o2", "emoji": "🎧", "text": "이어폰 크게 켜고 게임하며 걷기"}, {"id": "o3", "emoji": "🚸", "text": "횡단보도 앞에서 멈추기"}], "answer": "o2"},
    {"id": "life-01-traffic-safety-l3-q1", "topic": "교통안전", "prompt": "길을 건너기 전, 어디에 서 있어야 할까요?", "hint": "차도에서 한 발 물러나요.", "options": [{"id": "o1", "emoji": "🟨", "text": "보도(인도) 위 안전선 안쪽"}, {"id": "o2", "emoji": "🛣️", "text": "차도로 한 발 내려간 곳"}, {"id": "o3", "emoji": "🚗", "text": "차와 차 사이"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l3-q2", "topic": "교통안전", "prompt": "초록불이 켜졌어요. 어디로 건너야 안전할까요?", "hint": "하얀 줄무늬 길을 찾아요.", "options": [{"id": "o1", "emoji": "🚸", "text": "횡단보도 위로"}, {"id": "o2", "emoji": "↔️", "text": "횡단보도 옆 빈 도로로"}, {"id": "o3", "emoji": "🏃", "text": "가장 가까운 아무 곳으로"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l3-q3", "topic": "교통안전", "prompt": "길이 어두운 밤, 어디로 다니는 게 안전할까요?", "hint": "밝은 곳이 안전해요.", "options": [{"id": "o1", "emoji": "💡", "text": "가로등이 있는 밝은 인도"}, {"id": "o2", "emoji": "🌑", "text": "불 꺼진 골목 안쪽"}, {"id": "o3", "emoji": "🛣️", "text": "차가 다니는 도로 가장자리"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l3-q4", "topic": "교통안전", "prompt": "지하철을 기다릴 때 안전한 위치는?", "hint": "노란 선을 떠올려요.", "options": [{"id": "o1", "emoji": "🟡", "text": "노란 안전선 뒤"}, {"id": "o2", "emoji": "🚉", "text": "선로 바로 앞"}, {"id": "o3", "emoji": "🏃", "text": "문이 열리기 전 뛰어들기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l3-q5", "topic": "교통안전", "prompt": "골목에서 차가 다닐 때, 아이는 어디로 가야 할까요?", "hint": "벽 쪽으로 붙어요.", "options": [{"id": "o1", "emoji": "🧱", "text": "길 가장자리 벽 쪽으로 붙기"}, {"id": "o2", "emoji": "🛣️", "text": "길 한가운데로 걷기"}, {"id": "o3", "emoji": "🚗", "text": "차 뒤에 숨기"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l5-q1", "topic": "교통안전", "prompt": "상황을 보고 가장 안전한 행동을 골라보세요.", "hint": "차를 먼저 보내요.", "options": [{"id": "o1", "emoji": "🛑", "text": "멈추고 차가 지나간 뒤 이동한다"}, {"id": "o2", "emoji": "🏃", "text": "바로 뛰어서 지나간다"}, {"id": "o3", "emoji": "👬", "text": "친구를 따라 무작정 건넌다"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l5-q2", "topic": "교통안전", "prompt": "이럴 때 어떻게 해야 안전할까요?", "hint": "차가 멈추는지 꼭 확인해요.", "options": [{"id": "o1", "emoji": "👀", "text": "차가 멈추는지 확인하고 건넌다"}, {"id": "o2", "emoji": "🏃", "text": "초록불이니 그냥 뛰어 건넌다"}, {"id": "o3", "emoji": "📱", "text": "휴대폰을 보며 건넌다"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l5-q3", "topic": "교통안전", "prompt": "가장 안전한 행동은 무엇일까요?", "hint": "차도로 뛰어들면 위험해요.", "options": [{"id": "o1", "emoji": "🧑", "text": "어른에게 도움을 요청한다"}, {"id": "o2", "emoji": "🏃", "text": "바로 차도로 뛰어가 줍는다"}, {"id": "o3", "emoji": "🙈", "text": "차 사이로 몰래 들어간다"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l5-q4", "topic": "교통안전", "prompt": "비 오는 날, 가장 안전한 행동은?", "hint": "우산을 살짝 들어 앞을 봐요.", "options": [{"id": "o1", "emoji": "☂️", "text": "우산을 들어 앞을 보며 천천히 건넌다"}, {"id": "o2", "emoji": "🏃", "text": "우산으로 앞을 가린 채 뛴다"}, {"id": "o3", "emoji": "🚗", "text": "차가 서줄 거라 믿고 그냥 건넌다"}], "answer": "o1"},
    {"id": "life-01-traffic-safety-l5-q5", "topic": "교통안전", "prompt": "가장 안전한 행동을 골라보세요.", "hint": "무리해서 차도로 나가지 않아요.", "options": [{"id": "o1", "emoji": "↩️", "text": "어른과 함께 안전한 길로 돌아간다"}, {"id": "o2", "emoji": "🛣️", "text": "차도로 내려가 빠르게 지나간다"}, {"id": "o3", "emoji": "🧗", "text": "공사 울타리를 넘어간다"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l1-q1", "topic": "화재안전", "prompt": "불이 났을 때 해야 할 행동을 골라보세요.", "hint": "어른에게 빨리 알려요.", "options": [{"id": "o1", "emoji": "🗣️", "text": "어른에게 알리기"}, {"id": "o2", "emoji": "🙈", "text": "이불 속에 숨기"}, {"id": "o3", "emoji": "🧸", "text": "장난감부터 챙기기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l1-q2", "topic": "화재안전", "prompt": "연기가 가득할 때 바른 행동은?", "hint": "연기는 위로 올라가요.", "options": [{"id": "o1", "emoji": "🧎", "text": "낮은 자세로 이동하기"}, {"id": "o2", "emoji": "🏃", "text": "똑바로 서서 뛰기"}, {"id": "o3", "emoji": "🤸", "text": "연기 쪽으로 다가가기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l1-q3", "topic": "화재안전", "prompt": "불이 났을 때 신고는 어디로 할까요?", "hint": "소방관 아저씨 번호예요.", "options": [{"id": "o1", "emoji": "🚒", "text": "119에 신고하기"}, {"id": "o2", "emoji": "👮", "text": "112에 신고하기"}, {"id": "o3", "emoji": "📞", "text": "114에 전화하기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l1-q4", "topic": "화재안전", "prompt": "옷에 불이 붙었을 때 해야 할 행동은?", "hint": "멈추고, 엎드리고, 뒹굴어요.", "options": [{"id": "o1", "emoji": "🤾", "text": "멈춰서 엎드려 굴러 끄기"}, {"id": "o2", "emoji": "🏃", "text": "더 빨리 뛰어다니기"}, {"id": "o3", "emoji": "🙌", "text": "손을 흔들며 소리만 지르기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l1-q5", "topic": "화재안전", "prompt": "대피할 때 안전한 행동을 골라보세요.", "hint": "계단으로 내려가요.", "options": [{"id": "o1", "emoji": "🚶", "text": "계단으로 대피하기"}, {"id": "o2", "emoji": "🛗", "text": "엘리베이터 타기"}, {"id": "o3", "emoji": "🚪", "text": "방문 잠그고 기다리기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l2-q1", "topic": "화재안전", "prompt": "불이 났을 때 하면 안 되는 행동을 찾아보세요.", "hint": "엘리베이터는 멈출 수 있어요.", "options": [{"id": "o1", "emoji": "🚶", "text": "계단으로 대피하기"}, {"id": "o2", "emoji": "🧎", "text": "낮은 자세로 이동하기"}, {"id": "o3", "emoji": "🛗", "text": "엘리베이터 타기"}], "answer": "o3"},
    {"id": "life-02-fire-safety-l2-q2", "topic": "화재안전", "prompt": "위험한 행동을 골라보세요.", "hint": "불 구경은 위험해요.", "options": [{"id": "o1", "emoji": "🏃", "text": "빨리 밖으로 대피하기"}, {"id": "o2", "emoji": "👀", "text": "불이 난 곳을 구경하기"}, {"id": "o3", "emoji": "📞", "text": "119에 신고하기"}], "answer": "o2"},
    {"id": "life-02-fire-safety-l2-q3", "topic": "화재안전", "prompt": "하면 안 되는 행동은 무엇일까요?", "hint": "연기를 마시면 위험해요.", "options": [{"id": "o1", "emoji": "😮‍💨", "text": "연기를 크게 들이마시며 이동"}, {"id": "o2", "emoji": "🧣", "text": "옷으로 코와 입 막기"}, {"id": "o3", "emoji": "🧎", "text": "낮게 엎드려 이동"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l2-q4", "topic": "화재안전", "prompt": "대피할 때 위험한 행동을 찾아보세요.", "hint": "물건보다 몸이 먼저예요.", "options": [{"id": "o1", "emoji": "🎮", "text": "게임기를 챙기러 다시 들어가기"}, {"id": "o2", "emoji": "🚪", "text": "문을 닫고 빠져나오기"}, {"id": "o3", "emoji": "🗣️", "text": "가족을 불러 함께 나가기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l2-q5", "topic": "화재안전", "prompt": "문을 열기 전 위험한 행동은?", "hint": "문이 뜨거우면 열면 안 돼요.", "options": [{"id": "o1", "emoji": "✋", "text": "뜨거운 문을 그냥 벌컥 열기"}, {"id": "o2", "emoji": "🤚", "text": "손등으로 문 온도 확인하기"}, {"id": "o3", "emoji": "🪟", "text": "다른 탈출로 찾아보기"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l5-q1", "topic": "화재안전", "prompt": "상황을 보고 안전한 행동을 골라보세요.", "hint": "가까이 가지 않아요.", "options": [{"id": "o1", "emoji": "🧑", "text": "어른에게 알리고 멀리 떨어진다"}, {"id": "o2", "emoji": "✋", "text": "가까이 가서 만져본다"}, {"id": "o3", "emoji": "💧", "text": "기름불에 물을 무조건 붓는다"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l5-q2", "topic": "화재안전", "prompt": "가장 안전한 행동은?", "hint": "문 밖에 불이 있을 수 있어요.", "options": [{"id": "o1", "emoji": "🪟", "text": "문을 열지 않고 다른 길을 찾는다"}, {"id": "o2", "emoji": "🚪", "text": "그냥 문을 벌컥 연다"}, {"id": "o3", "emoji": "🛌", "text": "침대에 숨는다"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l5-q3", "topic": "화재안전", "prompt": "이럴 때 어떻게 해야 할까요?", "hint": "만지지 말고 알려요.", "options": [{"id": "o1", "emoji": "🗣️", "text": "만지지 말고 어른에게 바로 알린다"}, {"id": "o2", "emoji": "💦", "text": "물을 뿌린다"}, {"id": "o3", "emoji": "🤚", "text": "플러그를 맨손으로 세게 뽑는다"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l5-q4", "topic": "화재안전", "prompt": "가장 안전한 행동을 골라보세요.", "hint": "연기가 적은 아래로 낮게 이동해요.", "options": [{"id": "o1", "emoji": "🧎", "text": "낮은 자세로 벽을 짚고 이동한다"}, {"id": "o2", "emoji": "🏃", "text": "똑바로 서서 뛴다"}, {"id": "o3", "emoji": "🛗", "text": "엘리베이터로 내려간다"}], "answer": "o1"},
    {"id": "life-02-fire-safety-l5-q5", "topic": "화재안전", "prompt": "나갈 수 없을 때 안전한 행동은?", "hint": "틈을 막고 구조를 기다려요.", "options": [{"id": "o1", "emoji": "🧴", "text": "젖은 수건으로 문틈을 막고 창가에서 구조 요청"}, {"id": "o2", "emoji": "🔥", "text": "연기 속으로 무작정 뛰어든다"}, {"id": "o3", "emoji": "🙈", "text": "옷장 안에 숨는다"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l1-q1", "topic": "손씻기", "prompt": "손을 깨끗하게 하는 행동을 골라보세요.", "hint": "비누를 사용해요.", "options": [{"id": "o1", "emoji": "🧼", "text": "비누로 손 씻기"}, {"id": "o2", "emoji": "🍚", "text": "손 안 씻고 밥 먹기"}, {"id": "o3", "emoji": "👕", "text": "옷에 손 닦기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l1-q2", "topic": "손씻기", "prompt": "언제 손을 씻어야 할까요?", "hint": "밥 먹기 전을 떠올려요.", "options": [{"id": "o1", "emoji": "🍽️", "text": "밥 먹기 전에"}, {"id": "o2", "emoji": "🎮", "text": "게임 이길 때만"}, {"id": "o3", "emoji": "😴", "text": "절대 씻지 않기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l1-q3", "topic": "손씻기", "prompt": "올바른 손 씻기 행동은?", "hint": "거품을 충분히 내요.", "options": [{"id": "o1", "emoji": "🫧", "text": "거품을 내서 30초 문지르기"}, {"id": "o2", "emoji": "⚡", "text": "물만 1초 스치기"}, {"id": "o3", "emoji": "🙅", "text": "손끝만 살짝 적시기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l1-q4", "topic": "손씻기", "prompt": "화장실을 다녀온 뒤 바른 행동은?", "hint": "꼭 씻어야 해요.", "options": [{"id": "o1", "emoji": "🧼", "text": "비누로 손을 깨끗이 씻기"}, {"id": "o2", "emoji": "🏃", "text": "그냥 뛰어나가기"}, {"id": "o3", "emoji": "🧻", "text": "휴지로만 닦고 끝내기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l1-q5", "topic": "손씻기", "prompt": "손을 씻은 뒤 바른 행동은?", "hint": "깨끗한 수건에 말려요.", "options": [{"id": "o1", "emoji": "🧻", "text": "깨끗한 수건으로 물기 닦기"}, {"id": "o2", "emoji": "👖", "text": "더러운 바지에 닦기"}, {"id": "o3", "emoji": "💦", "text": "젖은 채로 그냥 두기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l4-q1", "topic": "손씻기", "prompt": "손 씻기에 알맞지 않은 행동을 찾아보세요.", "hint": "옷에 닦으면 안 돼요.", "options": [{"id": "o1", "emoji": "💧", "text": "손에 물 묻히기"}, {"id": "o2", "emoji": "🧼", "text": "비누로 문지르기"}, {"id": "o3", "emoji": "👖", "text": "대충 옷에 닦기"}], "answer": "o3"},
    {"id": "life-03-clean-hands-l4-q2", "topic": "손씻기", "prompt": "올바른 손 씻기가 아닌 것은?", "hint": "물만 스치면 안 돼요.", "options": [{"id": "o1", "emoji": "⚡", "text": "물에 1초만 담갔다 빼기"}, {"id": "o2", "emoji": "🫧", "text": "거품 내서 문지르기"}, {"id": "o3", "emoji": "🧻", "text": "깨끗이 헹구고 말리기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l4-q3", "topic": "손씻기", "prompt": "손 씻기에 맞지 않는 행동을 골라보세요.", "hint": "비누를 건너뛰면 안 돼요.", "options": [{"id": "o1", "emoji": "🚫", "text": "비누 없이 물로만 대충 씻기"}, {"id": "o2", "emoji": "🧼", "text": "비누로 골고루 문지르기"}, {"id": "o3", "emoji": "🖐️", "text": "손가락 사이도 씻기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l4-q4", "topic": "손씻기", "prompt": "위생에 좋지 않은 행동은?", "hint": "더러운 수건은 안 돼요.", "options": [{"id": "o1", "emoji": "🧽", "text": "더럽고 축축한 걸레로 닦기"}, {"id": "o2", "emoji": "🧻", "text": "깨끗한 수건으로 닦기"}, {"id": "o3", "emoji": "💨", "text": "손 건조기로 말리기"}], "answer": "o1"},
    {"id": "life-03-clean-hands-l4-q5", "topic": "손씻기", "prompt": "손 씻기에 알맞지 않은 행동을 찾아보세요.", "hint": "거품을 바로 씻어내면 안 돼요.", "options": [{"id": "o1", "emoji": "⏱️", "text": "거품 내자마자 바로 헹구기"}, {"id": "o2", "emoji": "🔄", "text": "손등과 손바닥 모두 문지르기"}, {"id": "o3", "emoji": "💅", "text": "손톱 밑도 깨끗이 씻기"}], "answer": "o1"},
    {"id": "life-06-digital-safety-l5-q1", "topic": "디지털 안전", "prompt": "가장 위험한 스마트폰 화면을 골라보세요.", "hint": "개인정보를 요구하는 화면이 위험해요.", "options": [{"id": "o1", "emoji": "🎮", "text": "게임 시작 화면"}, {"id": "o2", "emoji": "🔒", "text": "비밀번호와 집 주소를 입력하라는 화면"}, {"id": "o3", "emoji": "🧑", "text": "부모님께 확인하라는 화면"}], "answer": "o2"},
    {"id": "life-06-digital-safety-l5-q2", "topic": "디지털 안전", "prompt": "가장 위험한 화면을 골라보세요.", "hint": "공짜 선물로 정보를 요구하면 위험해요.", "options": [{"id": "o1", "emoji": "📖", "text": "동화책 읽기 화면"}, {"id": "o2", "emoji": "🎁", "text": "무료 선물 줄테니 주소 적으라는 화면"}, {"id": "o3", "emoji": "🎨", "text": "그림 그리기 화면"}], "answer": "o2"},
    {"id": "life-06-digital-safety-l5-q3", "topic": "디지털 안전", "prompt": "가장 위험한 화면을 골라보세요.", "hint": "낯선 사람이 만나자는 화면이 위험해요.", "options": [{"id": "o1", "emoji": "💬", "text": "낯선 사람이 몰래 만나자는 채팅 화면"}, {"id": "o2", "emoji": "🎵", "text": "동요 듣기 화면"}, {"id": "o3", "emoji": "🧮", "text": "수학 문제 풀기 화면"}], "answer": "o1"},
    {"id": "life-06-digital-safety-l5-q4", "topic": "디지털 안전", "prompt": "가장 위험한 화면을 골라보세요.", "hint": "결제 정보를 몰래 요구하면 위험해요.", "options": [{"id": "o1", "emoji": "📺", "text": "학습 영상 화면"}, {"id": "o2", "emoji": "💳", "text": "부모님 카드번호를 입력하라는 화면"}, {"id": "o3", "emoji": "🐱", "text": "캐릭터 꾸미기 화면"}], "answer": "o2"},
    {"id": "life-06-digital-safety-l5-q5", "topic": "디지털 안전", "prompt": "가장 위험한 화면을 골라보세요.", "hint": "수상한 앱을 설치하라는 화면이 위험해요.", "options": [{"id": "o1", "emoji": "🧩", "text": "퍼즐 게임 화면"}, {"id": "o2", "emoji": "⬇️", "text": "\"지금 설치하면 상품!\" 이라는 화면"}, {"id": "o3", "emoji": "📖", "text": "전자책 화면"}], "answer": "o2"},
    {"id": "life-10-lost-child-l1-q1", "topic": "미아 안전", "prompt": "길을 잃었을 때 도움을 받을 수 있는 곳을 골라보세요.", "hint": "어른들이 도와주는 곳이에요.", "options": [{"id": "o1", "emoji": "👮", "text": "경찰서"}, {"id": "o2", "emoji": "🚗", "text": "모르는 사람 차"}, {"id": "o3", "emoji": "🌑", "text": "어두운 골목"}], "answer": "o1"},
    {"id": "life-10-lost-child-l1-q2", "topic": "미아 안전", "prompt": "마트에서 길을 잃었어요. 어디로 가야 할까요?", "hint": "직원이 있는 곳을 찾아요.", "options": [{"id": "o1", "emoji": "🛎️", "text": "안내데스크"}, {"id": "o2", "emoji": "🚪", "text": "마트 밖 주차장"}, {"id": "o3", "emoji": "🚗", "text": "낯선 아저씨를 따라가기"}], "answer": "o1"},
    {"id": "life-10-lost-child-l1-q3", "topic": "미아 안전", "prompt": "도움을 요청하기 좋은 안전한 사람을 골라보세요.", "hint": "제복을 입은 사람을 찾아요.", "options": [{"id": "o1", "emoji": "👮", "text": "경찰관·안전요원"}, {"id": "o2", "emoji": "🕶️", "text": "따라오라는 낯선 사람"}, {"id": "o3", "emoji": "🚗", "text": "태워주겠다는 사람"}], "answer": "o1"},
    {"id": "life-10-lost-child-l1-q4", "topic": "미아 안전", "prompt": "길을 잃었을 때 안전한 장소를 골라보세요.", "hint": "사람이 많고 밝은 곳이 안전해요.", "options": [{"id": "o1", "emoji": "🏪", "text": "편의점(직원에게 도움 요청)"}, {"id": "o2", "emoji": "🌑", "text": "사람 없는 어두운 길"}, {"id": "o3", "emoji": "🅿️", "text": "지하 주차장"}], "answer": "o1"},
    {"id": "life-10-lost-child-l1-q5", "topic": "미아 안전", "prompt": "학교 근처에서 길을 잃으면 누구에게 도움을 청할까요?", "hint": "믿을 수 있는 어른이에요.", "options": [{"id": "o1", "emoji": "🧑‍🏫", "text": "선생님·학교 보안관"}, {"id": "o2", "emoji": "🚗", "text": "차에 타라는 사람"}, {"id": "o3", "emoji": "🎁", "text": "선물 준다는 낯선 사람"}], "answer": "o1"},
]

_BY_ID = {q["id"]: q for q in LIFE_QUESTIONS}


def get_question(qid: str) -> dict | None:
    return _BY_ID.get(qid)


def public_question(q: dict) -> dict:
    """프론트로 내려줄 형태 — 정답 제거."""
    return {
        "id": q["id"],
        "topic": q["topic"],
        "prompt": q["prompt"],
        "hint": q["hint"],
        "options": q["options"],
    }
